AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation template to create an EFS FileSystem, MountTarget, and SecurityGroup

Parameters:
  VpcId:
    Description: The VPC ID where resources will be created
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Description: The Subnet ID for the Mount Target
    Type: AWS::EC2::Subnet::Id

Resources:
  EFSFileSystem:
    Type: "AWS::EFS::FileSystem"
    Properties:
      PerformanceMode: generalPurpose # Options: generalPurpose, maxIO
      Encrypted: true

  EFSFileSystemSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Security group for EFS FileSystem
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 2049
          ToPort: 2049
          CidrIp: "0.0.0.0/0"

  MountTarget:
    Type: "AWS::EFS::MountTarget"
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Ref SubnetId
      SecurityGroups:
        - !Ref EFSFileSystemSecurityGroup

Outputs:
  FileSystemId:
    Description: ID of the EFS FileSystem
    Value: !Ref EFSFileSystem
