AWSTemplateFormatVersion: 2010-09-09
Description: Launch EC2 instance with the latest Ubuntu AMI with SSM 

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: "/aws/service/canonical/ubuntu/server/noble/stable/current/amd64/hvm/ebs-gp3/ami-id"
  InstanceType:
    Type: String
    Default: t2.medium
    AllowedValues:
      - t2.medium
      - t2.large
      - t2.xlarge
      - c5.large
      - c5.xlarge
  VolumeSize:                                                                                                                     
    Type: Number                                                                                                                  
    Default: 20                                                                                                                   
    AllowedValues: [20, 40, 60, 80, 100] 

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      AvailabilityZone: !Ref AvailabilityZone
      IamInstanceProfile: !Ref MyInstanceProfile
      BlockDeviceMappings:             
        - DeviceName: "/dev/sda1"                                              
          Ebs:                         
            VolumeSize: !Ref VolumeSize    

      UserData: 
        Fn::Base64: !Sub |
         #!/bin/bash -xe
         sudo apt-get update -y
         sudo apt-get upgrade -y
         sudo apt -y install python3 pipx 
  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MyInstanceRole
  MyInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: /

Outputs:
  MyInstanceIP:
    Value: !GetAtt MyInstance.PublicIp
    Description: Instance public IP